### ISSUE TITLE
Optimize requests: send one or batched translation request(s)

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-ai-translator#27]
Currently, each of the N fields requiring translation sends a separate request, which can create performance issues when N is large, such as in content forms with hundreds of fields.

- Send one or multiple batch requests to translate the required fields, reducing the number of individual requests.
- Implement client part of the WS connection
- Update the backend to parse batch field requests and handle them as individual translations.
- Modify the backend to maintain an open websocket connection during translation and close it once complete.

Can be divided into multiple tasks.
```[tasklist]
### Tasks
- [ ] https://github.com/enonic/app-ai-translator/issues/32
- [ ] https://github.com/enonic/app-ai-translator/issues/43
- [ ] https://github.com/enonic/app-ai-translator/issues/46
```
